package com.sl.ue.role.main;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import com.sl.ue.hj.util.Db;

public class AddResource {

	public static void main(String[] args){
		Connection conn = Db.getConnection();
		try {
			Statement stmt = conn.createStatement();
			stmt.executeUpdate(sql, autoGeneratedKeys)
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}
